-- INSERT INTO user (username, password, name, surname, email, phone, birthday, gender, address, info, photo_url, status)
-- VALUES
--     ('admin', '$2a$10$buP1YFnhFWAhvONKgZH0muT7X.irpXklsiaR/C/YRQfEaA5EI1aOe', 'Admin', 'AdminSurname', 'admin@example.com', '123456789', '2000-01-01', 0, 'Admin Address', 'Admin Info', 'admin.jpg', 'ACTIVE');